### ISSUE TITLE
Last character of right prompt truncated in ghostty

### ISSUE THREAD

**Issue by Crocmagnon** [IlanCosman/tide#557]
#### Describe the bug

The last character of the right prompt is truncated in ghostty.
This only affects the right prompt and not the terminal output (see screenshot: "hello" is correctly printed).

#### Steps to reproduce

1. Open [Ghostty](https://ghostty.org/)
2. Trigger something on the right prompt (python venv, duration, signal, ...)
3. Observe

#### Screenshots

<img width="585" alt="image" src="https://github.com/user-attachments/assets/7e199650-9ba7-477f-bab0-7a5479da54f3" />

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.7.1
tide version: 6.1.1
term: xterm-ghostty
os: macOS 15.2 (24C101)
terminal emulator: Ghostty
fish startup: 39.22 millis
fisher plugins: jorgebucaran/fisher fisherman/z franciscolourenco/done jorgebucaran/autopair.fish patrickf1/fzf.fish ilancosman/tide@v6 catppuccin/fish
```

**Comment by Crocmagnon** [comment]
Looks like the issue has already been raised to Ghostty: https://github.com/ghostty-org/ghostty/issues/884

**Comment by Crocmagnon** [comment]
Workaround:
```fish
set tide_right_prompt_suffix " "
```

**Comment by bekanui** [comment]
This happens also in other terminals; this is a screenshot from Windows Terminal open in a WSL shell:

![Image](https://github.com/user-attachments/assets/ec1714c4-1504-445b-b450-853b201cb211)

From the linked thread on Ghostty, it seems like the problem should be fixed in Fish or Tide, since it could manifest in multiple terminals depending on how they handle writing a character in the last column:
https://github.com/ghostty-org/ghostty/issues/884#issuecomment-1813185031

**Comment by TRPB** [comment]
which version should this be in? Fish 4.0.2 doesn't fix it for me
